### ISSUE TITLE
Export Option for the Perk and Skill pages

### ISSUE THREAD

**Issue by Kenji3108** [zunath/SWLOR_Website#29]
Allow the skill and perk pages to be exported for ease of use by any potential future tools.

I had given thoughts on the format of which the export option would be in, maybe just an ASCII file and arrays of skills, perks, and their respective levels and SP cost of each level of perk and level requirement will suffice.

Oh, and separate skills and perks, please.

**Comment by zunath** [comment]
Would it be sufficient to use a JSON format?

**Comment by Kenji3108** [comment]
That might be even better! I had half a mind to write a small program in python to do all the grunt work of printing out all of those perks and their levels and cost.

**Comment by zunath** [comment]
Added this.
